name: Automatycznego budowanie pliku .exe z projektu

on:
  schedule:
    - cron: '0 0 * * 0' # co tydzień
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build
      run: pyinstaller --onefile --noconsole project.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: dist/project.exe
